#!/usr/bin/env bash

# Should return the latest version of the software as a string, 
# without any leading "v" or other characters.
fetch_latest_version() {
    latest=$(curl -sfL https://api.github.com/repos/example/repo/releases/latest | jq -r '.tag_name')
    latest="${latest#v}"

    echo "$latest"
}
